# To test with http://editor.swagger.io/
openapi: 3.0.0
info:
  title: TrikTrak Lairs API
  description: API Draft for TrikTrak Lairs
  version: 0.1.0
paths:
  /users:
    post:
      summary: Post user lairs
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: List of GMaps public_id
              type: array
              items:
                type: string
      responses:
        '200':    # status code
          description: User lairs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lair'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/MissingParam'
    get:
      summary: Get user lairs
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: User's lairs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lair'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    MissingParam:
      description: A parameter is missing
    NotFound:
      description: Resource not found
    BadRequest:
      description: Bad request
    BadParametersError:
      description: Unprocessable entity
    UnauthorizedAccess:
      description: User cannot access this resource
    TooManyRequests:
      description: User sent too many requests
  schemas:
    Lair:
      description: User's lair
      type: object
      properties:
        publicId:
          type: string
        name:
          type: string
        types:
          type: array
          items:
            type: string
        photos:
          type: array
          items:
            $ref: '#/components/schemas/Photo'
        address:
          type: string
        location:
          type: object
          properties:
            lng:
              type: number
            lat:
              type: number
    Photo:
      description: A lair photo
      type: object
      properties:
        height:
          type: integer
        width:
          type: integer
        url:
          type: string
      example:
        height: 40
        width: 40
        url: "http://images.triktrak.co/40x40_d0aads-sfea.jpg"
